apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esddns-operator-helm-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: esddns-prod
  source:
    repoURL: https://github.com/sqe/esddns
    targetRevision: HEAD
    path: helm/esddns-operator
    helm:
      releaseName: esddns-operator
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: replicaCount
          value: "3"
        - name: environment
          value: "production"
  destination:
    server: https://kubernetes.default.svc
    namespace: esddns-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
